/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "warm-editorial",
  "heroVariant": "split-image",
  "servicesVariant": "editorial-list",
  "navVariant": "top-bar",
  "footerVariant": "editorial-split",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-left",
  "galleryVariant": "masonry-3col",
  "sectionOrder": [
    "hero",
    "doctor-intro",
    "services",
    "gallery",
    "faq",
    "cta"
  ],
  "cardTreatment": "soft-shadow",
  "density": "airy",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "two-column alternating-row service layout with inline text and image pairs",
  "headingScale": "moderate",
  "sectionDivider": "space",
  "heroTextPosition": "center",
  "divergenceRationale": "All three recent builds used either editorial-asymmetric, magazine-split, or poster-hero with asymmetric-right or full-bleed heroes — this build moves to warm-editorial with a split-image hero to stay in the editorial/bold family (specialist positioning demands it) while introducing a genuinely different two-panel hero structure. Gallery floats above reviews in the vertical orthodontics prior but testimonials are absent from available data, so the section is omitted entirely and gallery fills that trust role instead. Stat-bar is also dropped — no data — keeping the layout honest rather than rendering placeholder dashes.",
  "creativeDirection": "A specialist practice that earns trust through composed restraint — cool-teal surfaces, generous white space, and editorial type pairings signal clinical authority while the split hero and portrait-forward doctor section keep the warmth a pediatric audience requires.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "Nunito (heading) / DM Sans (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#2A7A6F",
    "secondary": "#1D5C6B",
    "light": "#F0F9F7",
    "accent": "#F5A623",
    "highlight": "#E8F4F1"
  },
  "spacingScale": "4/8/16/32/64/96px",
  "writingTone": "Warm, clear, specific to Long Beach.",
  "brandSummary": "Pediatric Dental Specialists, led by Dr. Cortez, serving Long Beach, — A specialist practice that earns trust through composed restraint — cool-teal surfaces, generous white space, and editorial type pairings signal clinical authority while the split hero and portrait-forward doctor section keep the warmth a pediatric audience requires.",
  "doRules": [
    "Use the archetype's established warm-editorial layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be split-image — lock this choice.",
    "Card treatment is soft-shadow — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "soft-fill",
    "labelStyle": "inline",
    "sectionSpacing": "airy",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "centered",
    "servicesLayout": "accordion",
    "aboutLayout": "two-col-brief",
    "testimonialsLayout": "list-testimonials",
    "ctaLayout": "two-button",
    "faqLayout": "split-by-category",
    "navVariant": "top-bar",
    "footerVariant": "editorial-split",
    "galleryVariant": "masonry-3col",
    "typePersonality": "humanist-serif",
    "colorFamily": "warm"
  },
  "evalRationale": "Candidate 2 earns the edge through its tightest section logic — placing doctor-intro immediately after the hero front-loads the specialist credibility signal before services, then lets gallery serve as the trust-closer before FAQ, which is the most coherent narrative arc for a pediatric specialist with no reviews or stats. Its creative direction ('composed restraint') is the most specific and differentiated of the three, avoiding the generic 'children's hospital wing' metaphor of Candidate 1 and the slightly looser sequencing of Candidate 0."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
