// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    dropdown: [
      { label: 'Braces', href: '/services/braces', desc: '' },
      { label: 'Dental Care For Your Baby', href: '/services/dental-care-for-your-baby', desc: '' },
      { label: 'Dental Exams and Cleanings', href: '/services/dental-exams-and-cleanings', desc: '' },
      { label: 'Digit Sucking/Pacifier Use', href: '/services/digit-sucking-pacifier-use', desc: '' },
      { label: 'Emergencies', href: '/services/emergencies', desc: '' },
      { label: 'First Dental Visit', href: '/services/first-dental-visit', desc: '' },
      { label: 'Fluoride', href: '/services/fluoride', desc: '' },
      { label: 'Gum Disease Treatment', href: '/services/gum-disease-treatment', desc: '' },
      { label: 'All Services', href: '/services' },
    ],
  },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQ', href: '/faq' },
];
