// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Pediatric Dental Specialists',
  url: 'https://www.lbpds.net',
  phone: '(562) 377-1375',
  phoneDigits: '5623771375',
  email: '',
  googleReviewLink: '',
  googleProfileLink: '',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: 'Dr. Cortez',
  firstName: 'Cortez',
  lastName: '',
  nameNoTitle: 'Cortez',
  credentials: 'DDS',
  bio: "Welcome to Pediatric Dental Specialists located in Long Beach, California! We consider dental health to be an integral part of overall good health. We strive to make your child's first dental visit an enjoyable one. Young children receive a personalized storybook in which their name appears throughout the story. Our qualified professional team is dedicated to guiding our patients to obtain optimal oral health in a nurturing and friendly environment.",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
export const additionalDoctors = [
  {
    "name": "Dr. Gloria",
    "firstName": "Gloria",
    "lastName": "",
    "nameNoTitle": "Gloria",
    "credentials": "",
    "bio": "",
    "education": "",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Planells",
    "firstName": "Planells",
    "lastName": "",
    "nameNoTitle": "Planells",
    "credentials": "",
    "bio": "",
    "education": "",
    "specialties": [],
    "photoPath": "assets/images/img-dr-planells.jpg"
  }
];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

export const address = {
  street: '3320 N Los Coyotes Diagonal, Ste 200',
  city: 'Long Beach',
  state: 'CA',
  zip: '90808',
  country: 'US',
  full: '3320 N Los Coyotes Diagonal, Ste 200, Long Beach, CA 90808',
};

export const hours = {
  display: [
    { day: 'Mon', time: '9am – 5pm' },
    { day: 'Tue', time: '9am – 5pm' },
    { day: 'Wed', time: '9am – 5pm' },
    { day: 'Thu', time: '9am – 5pm' },
    { day: 'Fri', time: '9am – 5pm' },
    { day: 'Sat', time: 'Closed' },
    { day: 'Sun', time: 'Closed' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/PDSLongBeach',
    'https://www.instagram.com/pdslongbeach/',
    'https://twitter.com/PDSLongBeach',
    'https://www.youtube.com/channel/UCjPIfVHqnjIrKzet0eDUQpg',
    'http://www.yelp.com/biz/pediatric-dental-specialists-long-beach',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DDS Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  'knowsAbout': ["Pediatric Dentistry"],
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
