/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "card-heavy",
  "heroVariant": "centered",
  "servicesVariant": "cards-3up",
  "navVariant": "left-logo",
  "footerVariant": "bold-cta-footer",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-left",
  "galleryVariant": "featured-grid",
  "sectionOrder": [
    "hero",
    "doctor-intro",
    "services",
    "gallery",
    "reviews",
    "cta",
    "faq"
  ],
  "cardTreatment": "soft-shadow",
  "density": "balanced",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "thin-rule section dividers between content bands",
  "headingScale": "moderate",
  "sectionDivider": "line",
  "heroTextPosition": "center",
  "divergenceRationale": "All three prior builds used asymmetric or split hero variants (asymmetric-right, asymmetric-right, split-image) within the editorial-asymmetric, magazine-split, and warm-editorial archetypes — so any split or asymmetric hero and any editorial-family archetype is off the table. Card-heavy with a centered hero is a clean break: it lands in the classic/warm family (appropriate for a community neighborhood practice), produces a card-grid services layout and centered trust-forward hero, and has not appeared once in the recent build log. The vertical prior suggested gallery-first, but with doctor credibility (LANAP, DMD, dual-doctor) being the primary conversion lever and gallery data confirmed available, the IA best-practice sequence (trust → doctor → services → gallery → reviews → CTA) outweighs the orthodontic soft prior.",
  "creativeDirection": "A warm-authoritative card grid site where deep teal structural bands and muted gold thin-rule dividers give the layout clinical order, while centered humanist type and soft-shadow cards keep the neighborhood warmth intact — credibility you can feel before you read a word.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "Playfair Display (heading) / DM Sans (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#0e6b7a",
    "secondary": "#1a4a5c",
    "light": "#f0f7f8",
    "accent": "#c8a96e",
    "highlight": "#e8f4f6"
  },
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Long Beach.",
  "brandSummary": "Spring St. Dentistry, led by Dr. Anthony Hoang, serving Long Beach, — A warm-authoritative card grid site where deep teal structural bands and muted gold thin-rule dividers give the layout clinical order, while centered humanist type and soft-shadow cards keep the neighborhood warmth intact — credibility you can feel before you read a word.",
  "doRules": [
    "Use the archetype's established card-heavy layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be centered — lock this choice.",
    "Card treatment is soft-shadow — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "centered",
    "servicesLayout": "card-grid",
    "aboutLayout": "split-photo",
    "testimonialsLayout": "grid-mosaic",
    "ctaLayout": "two-button",
    "faqLayout": "cards-grid",
    "navVariant": "left-logo",
    "footerVariant": "bold-cta-footer",
    "galleryVariant": "featured-grid",
    "typePersonality": "humanist-serif",
    "colorFamily": "warm"
  },
  "evalRationale": "Candidate 0 wins on creative interest: the specific detail of 'deep teal structural bands and muted gold thin-rule dividers' giving 'clinical order' alongside 'centered humanist type' is the most evocative and distinctive creative direction of the three, and its unique section order (CTA before FAQ) shows deliberate IA thinking rather than a default template. Candidates 1 and 2 are nearly identical in both spec and creative language, making 0 the clear differentiator."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
