/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "poster-hero",
  "heroVariant": "poster",
  "servicesVariant": "editorial-list",
  "navVariant": "transparent-overlay",
  "footerVariant": "minimal-dark",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-left",
  "galleryVariant": "full-bleed-row",
  "sectionOrder": [
    "hero",
    "gallery",
    "doctor-intro",
    "services",
    "reviews",
    "cta",
    "faq"
  ],
  "cardTreatment": "soft-shadow",
  "density": "balanced",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "oversized type accent — a large-scale numeral or single word rendered at display size behind a content block, used as a structural graphic element rather than readable text",
  "headingScale": "moderate",
  "sectionDivider": "color-shift",
  "heroTextPosition": "bottom-left",
  "divergenceRationale": "All three prior builds occupy the split-image/full-bleed/asymmetric-right hero space paired with magazine-split, card-heavy, or warm-editorial archetypes — poster-hero with a bottom-left text anchor is the one unused combination that still sits comfortably in the editorial/bold family appropriate for an implants-and-LANAP-forward specialist practice. Centered-classic and warm-editorial were ruled out because the brand direction explicitly chose a grotesque heading face and a cool-dominant palette to differentiate from spa-dentistry competitors, which maps to the editorial family. Gallery is elevated above services per the vertical prior (orthodontics/cosmetic — outcome visuals convert before feature lists), and the soft color-shift divider between sections replaces the line or space dividers seen in prior builds.",
  "creativeDirection": "A confident, neighborhood-rooted editorial voice — the poster hero anchors the teal authority color at full saturation with the doctor's name and a plain-spoken outcome line sitting low-left like a broadsheet byline, while featured-grid gallery and alternating editorial-list services give the page a considered, unhurried premium feel that earns trust through specificity rather than decoration.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "Cormorant Garamond (heading) / DM Sans (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#0a6b7c",
    "secondary": "#1a4a5c",
    "light": "#f0f7f8",
    "accent": "#c9a96e",
    "highlight": "#e8f4f6"
  },
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Long Beach.",
  "brandSummary": "Spring St. Dentistry, led by Dr. Anthony Hoang, serving Long Beach, — A confident, neighborhood-rooted editorial voice — the poster hero anchors the teal authority color at full saturation with the doctor's name and a plain-spoken outcome line sitting low-left like a broadsheet byline, while featured-grid gallery and alternating editorial-list services give the page a considered, unhurried premium feel that earns trust through specificity rather than decoration.",
  "doRules": [
    "Use the archetype's established poster-hero layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be poster — lock this choice.",
    "Card treatment is soft-shadow — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "poster",
    "servicesLayout": "numbered-list",
    "aboutLayout": "split-photo",
    "testimonialsLayout": "pull-quotes",
    "ctaLayout": "centered-banner",
    "faqLayout": "simple-stack",
    "navVariant": "transparent-overlay",
    "footerVariant": "minimal-dark",
    "galleryVariant": "full-bleed-row",
    "typePersonality": "display-serif",
    "colorFamily": "cool"
  },
  "evalRationale": "Candidate 0 is the only entry that achieves genuine structural divergence from all three prior builds by using a poster-hero archetype with a bottom-left text anchor — a combination unused in the recent catalog — while its gallery-elevated section order and broadsheet editorial voice add specific creative interest that Candidates 1 and 2 lack entirely. Candidates 1 and 2 are near-identical centered-classic builds sharing the same archetype, hero variant, radius, motion, card treatment, and section order, making them redundant with each other and insufficiently distinct from the warm-editorial and magazine-split prior builds."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
