/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "editorial-asymmetric",
  "heroVariant": "asymmetric-left",
  "servicesVariant": "editorial-list",
  "navVariant": "centered-logo",
  "footerVariant": "minimal-dark",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-right",
  "galleryVariant": "editorial-2col",
  "sectionOrder": [
    "hero",
    "doctor-intro",
    "services",
    "gallery",
    "reviews",
    "faq",
    "cta"
  ],
  "cardTreatment": "soft-shadow",
  "density": "balanced",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "thin-rule section dividers between alternating content rows",
  "headingScale": "moderate",
  "sectionDivider": "line",
  "heroTextPosition": "bottom-left",
  "divergenceRationale": "All three previous builds used hero variants in the centered or right-split family (asymmetric-right, full-bleed, split-image); this build anchors the hero text bottom-left with an asymmetric-left layout, a distinct compositional grammar. The soft vertical prior pushed gallery above services, but with dental-implants as the primary emphasis and no stat-bar data, doctor credibility placed immediately after the hero earns more trust before services are introduced — so doctor-intro leads the mid-page. poster-hero and magazine-split were ruled out as direct repeats from the own-build history.",
  "creativeDirection": "A coastal specialist practice rendered in slate-teal and antique gold — editorial structure gives Dr. Hoang's named credibility and LANAP differentiation room to breathe, while the bottom-left hero anchor and thin-rule rhythm keep the tone unhurried and assured rather than loud.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "Playfair Display (heading) / DM Sans (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#0e6b82",
    "secondary": "#1a4a4e",
    "light": "#f0f8fa",
    "accent": "#c9a96e",
    "highlight": "#e8f4f7"
  },
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Long Beach.",
  "brandSummary": "Spring St. Dentistry, led by Dr. Anthony Hoang, serving Long Beach, — A coastal specialist practice rendered in slate-teal and antique gold — editorial structure gives Dr. Hoang's named credibility and LANAP differentiation room to breathe, while the bottom-left hero anchor and thin-rule rhythm keep the tone unhurried and assured rather than loud.",
  "doRules": [
    "Use the archetype's established editorial-asymmetric layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be asymmetric-left — lock this choice.",
    "Card treatment is soft-shadow — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "split",
    "servicesLayout": "alternating-rows",
    "aboutLayout": "full-width-card",
    "testimonialsLayout": "pull-quotes",
    "ctaLayout": "split-image",
    "faqLayout": "simple-stack",
    "navVariant": "centered-logo",
    "footerVariant": "minimal-dark",
    "galleryVariant": "editorial-2col",
    "typePersonality": "grotesque",
    "colorFamily": "cool"
  },
  "evalRationale": "Candidate 1 edges out Candidate 0 with nearly identical structure by grounding its creative direction in specific practice differentiators (LANAP, Dr. Hoang's named credibility) rather than generic editorial language, making it the most purposeful and least interchangeable of the three. Candidate 2 is penalized for surfacing gallery before doctor-intro, which undermines trust sequencing for a named specialist practice where credentials — not outcome volume — are the primary conversion lever."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
