// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    dropdown: [
      { label: 'Clear Aligners', href: '/services/clear-aligners', desc: '' },
      { label: 'Cosmetic Dentistry', href: '/services/cosmetic-dentistry', desc: '' },
      { label: 'Deep Cleaning', href: '/services/deep-cleaning', desc: '' },
      { label: 'Dental Bonding', href: '/services/dental-bonding', desc: '' },
      { label: 'Dental Bridges', href: '/services/dental-bridges', desc: '' },
      { label: 'Dental Crowns', href: '/services/dental-crowns', desc: '' },
      { label: 'Dental Fillings', href: '/services/dental-fillings', desc: '' },
      { label: 'Dental Implants', href: '/services/dental-implants', desc: '' },
      { label: 'All Services', href: '/services' },
    ],
  },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQ', href: '/faq' },
];
