// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Spring St. Dentistry',
  url: 'https://www.springstdentistry.com',
  phone: '(562) 420-8578',
  phoneDigits: '5624208578',
  email: '',
  googleReviewLink: 'https://www.google.com/maps/place/Spring+St.+Dentistry/@33.766568,-118.0842986,13z/data=!4m6!3m5!1s0x80dd2e06b18264df:0x5859cb8cd370dcb8!8m2!3d33.8097103!4d-118.1057071!16s%2Fg%2F1tx1thg9?entry=ttu',
  googleProfileLink: 'https://www.google.com/maps/place/Spring+St.+Dentistry/@33.766568,-118.0842986,13z/data=!4m6!3m5!1s0x80dd2e06b18264df:0x5859cb8cd370dcb8!8m2!3d33.8097103!4d-118.1057071!16s%2Fg%2F1tx1thg9?entry=ttu',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: 'Dr. Anthony Hoang',
  firstName: 'Anthony',
  lastName: 'Hoang',
  nameNoTitle: 'Anthony Hoang',
  credentials: 'DMD',
  bio: "Dr. Anthony Hoang was born and raised in Long Beach and Lakewood, and feels a true sense of pride and honor to have a dental practice in his hometown. He attended local schools at Lakewood High School and UC Irvine. He received his DMD degree from Tufts University School of Dental Medicine located in Boston, Massachusetts in 2014 and completed an additional year of General Practice Residency in Dentistry at the Loma Linda VA Medical Center where he provided comprehensive dental care to the veteran population. Dr. Hoang's favorite aspects of dentistry are the interpersonal relationships he develops with his patients and making them feel at ease during their dental visits. He looks forward to meeting all of his patients and providing high quality comprehensive dentistry for all of their needs. Dr. Hoang enjoys giving back to the community and has volunteered at nonprofit organizations such as the Long Beach Children's Dental Health Clinic, Boston public schools outreach programs, federal medical centers, and the Autumn Years Alzheimer's care facility.",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
export const additionalDoctors = [
  {
    "name": "Dr. Richard K. Lee",
    "firstName": "Richard",
    "lastName": "Lee",
    "nameNoTitle": "Richard K. Lee",
    "credentials": "Board-Certified Periodontist",
    "bio": "Dr. Richard Kang Lee is a board-certified periodontist. Before completing his residency in periodontics at Tufts University in Boston, he practiced general dentistry for 6 years in Southern California. This invaluable experience provided him with a comprehensive approach to dentistry and periodontics. To provide a wide range of treatment options for his patients, he has completed training in laser-assisted periodontal therapy and is a LANAP-certified clinician. He enjoys collaborating with restorative providers in delivering the best long-term treatment outcomes for health, stability, and esthetics. Dr. Lee is an active member of the American Dental Association(ADA), California Dental Association(CDA), California Society of Periodontists (CSP), and the American Academy of Periodontology (AAP). He has lectured at the West Coast Study Club and is faculty for the live surgical implant course with Hiossen. Dr. Richard Lee met his wife Jennifer in dental school at Tufts University. Following graduation in 2013, both relocated to California to work in private practice.",
    "education": "",
    "specialties": [],
    "photoPath": "https://www.springstdentistry.com/client/images/dr-lee.jpg"
  }
];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

export const address = {
  street: '6514 E. Spring St.',
  city: 'Long Beach',
  state: 'CA',
  zip: '90815',
  country: 'US',
  full: '6514 E. Spring St., Long Beach, CA 90815',
};

export const hours = {
  display: [
    { day: 'Mon–Thu', time: '9:00AM–6:00PM' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/SpringStDentistry',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DMD Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  'description': doctor.bio,
  'alumniOf': 'DMD from Tufts University School of Dental Medicine (2014), General Practice Residency at Loma Linda VA Medical Center, Lakewood High School, UC Irvine',
  'knowsAbout': ["General Dentistry","Family Dentistry","Cosmetic Dentistry"],
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
