/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "editorial-asymmetric",
  "heroVariant": "poster",
  "servicesVariant": "editorial-list",
  "navVariant": "centered-logo",
  "footerVariant": "minimal-dark",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-right",
  "galleryVariant": "editorial-2col",
  "sectionOrder": [
    "hero",
    "stat-bar",
    "gallery",
    "doctor-intro",
    "services",
    "reviews",
    "cta",
    "faq"
  ],
  "cardTreatment": "bordered-flat",
  "density": "balanced",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "thin-rule section dividers separating content bands",
  "headingScale": "dramatic",
  "sectionDivider": "line",
  "heroTextPosition": "bottom-left",
  "divergenceRationale": "All three recent builds used split-image or full-bleed hero variants with magazine-split or warm-editorial archetypes — this build instead uses a poster hero with bottom-left anchored type, drawing from institutional print design (annual reports, museum catalogues) rather than consumer health marketing. The editorial-asymmetric archetype was chosen over magazine-split (used in spring-st-dentistry) to produce alternating-row service treatments and pull-quote testimonials that reinforce specialist authority rather than consumer accessibility. Warm-editorial was explicitly avoided as it belongs to the classic/warm family and conflicts with the cool deep-navy palette and specialist positioning.",
  "creativeDirection": "The site reads like a credentialing document brought to life — deep navy structural bands, gold reserved exclusively for FACD designation callouts and primary CTAs, and Space Grotesk headlines set at dramatic scale to signal institutional confidence rather than consumer friendliness. Every layout decision prioritizes the specialist credential story: gallery surfaces outcome proof early, the stat-bar anchors peer-elected fellowship data above the fold, and the doctor intro positions Dr. Chang as a regional authority rather than a neighborhood provider.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "Cormorant Garamond (heading) / DM Sans (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#2C3E50",
    "secondary": "#4A6741",
    "light": "#F5F3EF",
    "accent": "#B8924A",
    "highlight": "#D4AF7A"
  },
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Los Alamitos.",
  "brandSummary": "Chang Orthodontics, led by Dr. Russell Chang, serving Los Alamitos, — The site reads like a credentialing document brought to life — deep navy structural bands, gold reserved exclusively for FACD designation callouts and primary CTAs, and Space Grotesk headlines set at dramatic scale to signal institutional confidence rather than consumer friendliness. Every layout decision prioritizes the specialist credential story: gallery surfaces outcome proof early, the stat-bar anchors peer-elected fellowship data above the fold, and the doctor intro positions Dr. Chang as a regional authority rather than a neighborhood provider.",
  "doRules": [
    "Use the archetype's established editorial-asymmetric layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be poster — lock this choice.",
    "Card treatment is bordered-flat — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "split",
    "servicesLayout": "alternating-rows",
    "aboutLayout": "full-width-card",
    "testimonialsLayout": "pull-quotes",
    "ctaLayout": "split-image",
    "faqLayout": "simple-stack",
    "navVariant": "centered-logo",
    "footerVariant": "minimal-dark",
    "galleryVariant": "editorial-2col",
    "typePersonality": "grotesque",
    "colorFamily": "cool"
  },
  "evalRationale": "Candidate 1 edges out the others with the most specific and evocative creative direction — 'credentialing document brought to life' with explicit references to Space Grotesk at dramatic scale and a clear rationale for each section's role in the specialist authority narrative — giving it the strongest creative interest score. Candidates 0 and 2 share nearly identical DNA but are slightly less precise in articulating how individual layout decisions serve the brand brief, while Candidate 2's CTA-last section order is a minor structural weakness for conversion."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
