// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    dropdown: [
      { label: 'Cleft Lip and Palate Treatment', href: '/services/cleft-lip-and-palate-treatment', desc: '' },
      { label: 'Craniofacial Orthodontics', href: '/services/craniofacial-orthodontics', desc: '' },
      { label: 'Damon Smile', href: '/services/damon-smile', desc: '' },
      { label: 'Dentofacial Orthopedics', href: '/services/dentofacial-orthopedics', desc: '' },
      { label: 'Digital X-rays', href: '/services/digital-x-rays', desc: '' },
      { label: 'Early Orthodontic Treatment', href: '/services/early-orthodontic-treatment', desc: '' },
      { label: 'Emergency Care', href: '/services/emergency-care', desc: '' },
      { label: 'In-Ovation Braces', href: '/services/in-ovation-braces', desc: '' },
      { label: 'All Services', href: '/services' },
    ],
  },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQ', href: '/faq' },
];
