// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Chang Orthodontics',
  url: 'https://www.changorthodontics.com',
  phone: '(562) 430-0541',
  phoneDigits: '5624300541',
  email: '',
  googleReviewLink: 'http://search.google.com/local/writereview?placeid=ChIJLU275-0u3YARKvs_iQAweo8',
  googleProfileLink: '',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: 'Dr. Russell Chang',
  firstName: 'Russell',
  lastName: 'Chang',
  nameNoTitle: 'Russell Chang',
  credentials: 'DDS, MS, FACD',
  bio: "Dr. Russell Chang and Dr. Christine Chung, USC Adjunct Assistant Professors of Postdoctoral Orthodontics and Pediatric Dentistry carefully create beautiful signature Chang Smiles utilizing the highest standards and newest technology in the most efficient and streamlined time of treatment. Over 40 years of Quality Care in Los Alamitos. Diplomate American Board of Orthodontics.",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
export const additionalDoctors = [
  {
    "name": "Dr. Christine Chung",
    "firstName": "Christine",
    "lastName": "Chung",
    "nameNoTitle": "Christine Chung",
    "credentials": "",
    "bio": "Dr. Christine Chung is a USC Adjunct Assistant Professor of Postdoctoral Orthodontics and Pediatric Dentistry who carefully creates beautiful signature Chang Smiles utilizing the highest standards and newest technology in the most efficient and streamlined time of treatment.",
    "education": "",
    "specialties": [],
    "photoPath": null
  }
];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

export const address = {
  street: '4608 Katella Ave STE 201',
  city: 'Los Alamitos',
  state: 'CA',
  zip: '90720',
  country: 'US',
  full: '4608 Katella Ave STE 201, Los Alamitos, CA 90720',
};

export const hours = {
  display: [
    { day: 'Mon', time: '7:45 a.m. – 5:00 p.m.' },
    { day: 'Tue', time: '7:45 a.m. – 5:00 p.m.' },
    { day: 'Wed', time: '7:45 a.m. – 5:00 p.m.' },
    { day: 'Thu', time: '7:45 a.m. – 5:00 p.m.' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/changortho/',
    'https://www.instagram.com/changorthodontics/',
    'https://twitter.com/DrChangOrtho',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DDS, MS, FACD Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  'description': doctor.bio,
  'alumniOf': 'USC Adjunct Assistant Professor of Postdoctoral Orthodontics',
  'knowsAbout': ["Orthodontics","Board Certified Orthodontist"],
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
