/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "editorial-asymmetric",
  "heroVariant": "split-image",
  "servicesVariant": "editorial-list",
  "navVariant": "centered-logo",
  "footerVariant": "minimal-dark",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-left",
  "galleryVariant": "editorial-2col",
  "sectionOrder": [
    "hero",
    "stat-bar",
    "gallery",
    "reviews",
    "cta",
    "services"
  ],
  "cardTreatment": "soft-shadow",
  "density": "balanced",
  "motion": "subtle",
  "radius": "md",
  "borrowedFrom": null,
  "borrowedTrait": "two-column rhythm with a fixed-width left label column and full-bleed right content column used as a recurring layout device across sections",
  "headingScale": "moderate",
  "sectionDivider": "space",
  "heroTextPosition": "bottom-left",
  "divergenceRationale": "Every recent own-build using editorial-asymmetric paired it with asymmetric-right or asymmetric-left hero variants — this build breaks that by using split-image, which creates a true vertical bisect between image and text rather than an overlay composition. The bearcreekfamilydentistry prior build already used editorial-asymmetric with asymmetric-right, so split-image is the sharpest departure while remaining coherent with the forest-teal editorial personality. Services are omitted entirely since no service data exists, keeping the layout honest rather than templated.",
  "creativeDirection": "A cool-rooted editorial voice built around the forest teal and muted gold palette — every section uses a disciplined two-column rhythm that feels like a design-forward independent publication, giving Bear Creek immediate visual authority without sacrificing the warmth the gold accent provides.",
  "coverage": {
    "filteredSections": [
      {
        "section": "doctor-intro",
        "reason": "no doctor name extracted from silver step",
        "signal": "doctor"
      }
    ]
  },
  "typographyScale": "16/20/28/40/56px",
  "colorPalette": "(from design phase)",
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Dallas.",
  "brandSummary": "Bear Creek Family Dentistry, serving Dallas, — A cool-rooted editorial voice built around the forest teal and muted gold palette — every section uses a disciplined two-column rhythm that feels like a design-forward independent publication, giving Bear Creek immediate visual authority without sacrificing the warmth the gold accent provides.",
  "doRules": [
    "Use the archetype's established editorial-asymmetric layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be split-image — lock this choice.",
    "Card treatment is soft-shadow — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "moderate",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "split",
    "servicesLayout": "alternating-rows",
    "aboutLayout": "full-width-card",
    "testimonialsLayout": "pull-quotes",
    "ctaLayout": "split-image",
    "faqLayout": "simple-stack",
    "navVariant": "centered-logo",
    "footerVariant": "minimal-dark",
    "galleryVariant": "editorial-2col",
    "typePersonality": "grotesque",
    "colorFamily": "cool"
  },
  "evalRationale": "Candidate 2 wins on layout variety and coherence: the split hero creates a true vertical bisect (not a poster overlay) that pairs cleanly with alternating-rows services and pull-quotes into a disciplined two-column editorial system — every section reinforces the same compositional logic. Candidates 0 and 1 both describe a poster-hero with bottom-left typographic lockup, making them near-identical in archetype despite different labels, and the poster format risks the centered-text-over-dark-photo penalty if the lockup drifts; Candidate 2's split-image hero is the sharpest structural departure while remaining coherent with the forest-teal editorial personality.",
  "borderTreatment": "hairline",
  "_contentPlanSections": [
    "hero",
    "services",
    "reviews",
    "stat-bar",
    "cta",
    "gallery"
  ]
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
