// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About', href: '/about', dropdown: [{ label: 'Blog', href: '/blog' }] },
  { label: 'Services', href: '/services', dropdown: [{ label: 'Dental Checkups and Cleanings', href: '/services/dental-checkups-and-cleanings' }, { label: 'Gum Disease Therapy', href: '/services/gum-disease-therapy' }, { label: 'Prosthodontics', href: '/services/prosthodontics' }, { label: 'Dental Crowns', href: '/services/dental-crowns' }, { label: 'Dental Bridges', href: '/services/dental-bridges' }, { label: 'Tooth-Colored Fillings', href: '/services/tooth-colored-fillings' }, { label: 'Dentures', href: '/services/dentures' }, { label: 'Root Canal Treatment', href: '/services/root-canal-treatment' }, { label: 'Pediatric Dentistry', href: '/services/pediatric-dentistry' }, { label: 'Special Needs Dentistry', href: '/services/special-needs-dentistry' }] },
  { label: 'Contact', href: '/contact', dropdown: [{ label: 'Dallas', href: '/contact' }] },
];
