// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Bear Creek Family Dentistry',
  url: 'https://www.bearcreekfamilydentistry.com',
  phone: '(888) 676-2327',
  phoneDigits: '8886762327',
  email: 'info@bearcreekfamilydentistry.com',
  googleReviewLink: 'https://www.google.com/maps/place/Bear+Creek+Family+Dentistry+-+Mesquite/@32.7946929,-96.612542,17z/data=!3m1!4b1!4m5!3m4!1s0x864ea5c7d582168d:0xd11b21413971c1dc!8m2!3d32.7946929!4d-96.6103533',
  googleProfileLink: 'https://www.google.com/maps/place/Bear+Creek+Family+Dentistry+-+Mesquite/@32.7946929,-96.612542,17z/data=!3m1!4b1!4m5!3m4!1s0x864ea5c7d582168d:0xd11b21413971c1dc!8m2!3d32.7946929!4d-96.6103533',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: '',
  firstName: '',
  lastName: '',
  nameNoTitle: '',
  credentials: 'DDS',
  // Bio MUST come from the doctor's own about/bio page. We never fall back to
  // practice.aboutText / mission copy — that produces the "bio bleed" bug
  // where the practice's philosophy ends up posing as a doctor's biography.
  bio: "",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
// (Back-compat mirror of doctors[1..] — new templates should use `doctors` directly.)
export const additionalDoctors = [];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

// Non-doctor staff (hygienists, dental assistants, receptionists, office
// managers). Rendered as the supporting team on /about and /team pages.
// Empty for practices with no staff captured.
export const staff = [];

export const address = {
  street: '4470 W. Jefferson Blvd., Suite 500',
  city: 'Dallas',
  state: 'TX',
  zip: '75211',
  country: 'US',
  full: '4470 W. Jefferson Blvd., Suite 500, Dallas, TX 75211',
};

export const hours = {
  display: [
    { day: 'Mon', time: '9:00am - 6:00pm' },
    { day: 'Tue', time: '9:00am - 6:00pm' },
    { day: 'Wed', time: '9:00am - 6:00pm' },
    { day: 'Thu', time: '9:00am - 6:00pm' },
    { day: 'Fri', time: 'Closed' },
    { day: 'Sat', time: '8:00am - 4:00pm' },
    { day: 'Sun', time: 'Closed' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'aggregateRating': {
    '@type': 'AggregateRating',
    'ratingValue': 4.9,
    'reviewCount': 2629,
    'bestRating': 5,
  },
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/Bear-Creek-Family-Dentistry-1657390287895980/',
    'https://www.facebook.com/pg/BCFDCockrellHill/reviews/',
    'https://www.yelp.com/biz/bear-creek-family-dentistry-dallas-3',
    'https://www.facebook.com/pg/BCFDWestcliff/reviews/',
    'https://www.facebook.com/pg/BCFDPecanPlaza/reviews/',
    'https://www.facebook.com/pg/BCFDSpringValley/reviews/',
    'https://www.facebook.com/pg/BCFDBuckner/reviews/',
    'https://www.facebook.com/pg/BCFDTorreVista/reviews/',
    'https://www.facebook.com/pg/BCFDTownNorth/reviews/',
    'https://www.facebook.com/pg/BCFDPioneer/reviews/',
    'https://www.facebook.com/pg/BCFDFortWorth/reviews/?ref=page_internal',
    'https://www.facebook.com/Bear-Creek-Family-Dentistry-Mesquite-472066193130050/',
    'https://www.facebook.com/BCFDDuncanville/reviews/?ref=page_internal',
    'https://www.facebook.com/BCFamilyDentistryDallas/',
    'https://www.google.com/maps/place/Bear+Creek+Family+Dentistry+-+Mesquite/@32.7946929,-96.612542,17z/data=!3m1!4b1!4m5!3m4!1s0x864ea5c7d582168d:0xd11b21413971c1dc!8m2!3d32.7946929!4d-96.6103533',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DDS Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
