// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'New Patients: Start Here', href: '/about' },
];
