// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Dentiq Dentistry',
  url: 'https://www.dentiq.dental',
  phone: '(713) 526-2904',
  phoneDigits: '7135262904',
  email: 'date@dentiq.net',
  googleReviewLink: 'https://www.google.com/maps/place/Dentiq+Dentistry/@29.7528012,-95.3976363,15z/data=!4m5!3m4!1s0x0:0x29dc8ade446d2c07!8m2!3d29.7528012!4d-95.3976363',
  googleProfileLink: 'https://www.google.com/maps/place/Dentiq+Dentistry/@29.7528012,-95.3976363,15z/data=!4m5!3m4!1s0x0:0x29dc8ade446d2c07!8m2!3d29.7528012!4d-95.3976363',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: '',
  firstName: '',
  lastName: '',
  nameNoTitle: '',
  credentials: 'DDS',
  // Bio MUST come from the doctor's own about/bio page. We never fall back to
  // practice.aboutText / mission copy — that produces the "bio bleed" bug
  // where the practice's philosophy ends up posing as a doctor's biography.
  bio: "",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
// (Back-compat mirror of doctors[1..] — new templates should use `doctors` directly.)
export const additionalDoctors = [];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

// Non-doctor staff (hygienists, dental assistants, receptionists, office
// managers). Rendered as the supporting team on /about and /team pages.
// Empty for practices with no staff captured.
export const staff = [];

export const address = {
  street: '1355 W Gray St',
  city: 'Houston',
  state: 'TX',
  zip: '77019',
  country: 'US',
  full: '1355 W Gray St, Houston, TX 77019',
};

export const hours = {
  display: [
    { day: 'Mon', time: '8:00 am - 12:00 pm' },
    { day: 'Tue', time: '7:00 am - 3:00 pm' },
    { day: 'Wed', time: '7:00 am - 3:00 pm' },
    { day: 'Thu', time: '7:00 am - 3:00 pm' },
    { day: 'Fri', time: '7:00 am - 3:00 pm' },
    { day: 'Sat', time: 'Closed' },
    { day: 'Sun', time: 'Closed' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'aggregateRating': {
    '@type': 'AggregateRating',
    'ratingValue': 4.9,
    'reviewCount': 1246,
    'bestRating': 5,
  },
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/dentiqdentistry/',
    'https://x.com/dentiq_dentist',
    'https://www.instagram.com/dentiqdentistry/?hl=en',
    'https://www.youtube.com/channel/UCd4c-mFQaBZ4cJGhYS8GEuA/videos',
    'https://www.yelp.com/biz/dentiq-dentistry-houston-2',
    'https://maps.google.com/maps?cid=3016438537666767879',
    'https://www.google.com/maps/place/Dentiq+Dentistry/@29.7528012,-95.3976363,15z/data=!4m5!3m4!1s0x0:0x29dc8ade446d2c07!8m2!3d29.7528012!4d-95.3976363',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DDS Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
