/**
 * Design DNA — generated by Creative Director phase.
 * Do not hand-edit; overwrite by re-running the pipeline.
 */

export interface DesignTokens {
  cornerRadius:       'sharp' | 'moderate' | 'rounded' | 'full';
  buttonTreatment:    'filled' | 'outline' | 'soft-fill';
  labelStyle:         'inline' | 'badge';
  sectionSpacing:     'compact' | 'default' | 'airy';
  contentDensity:     'tight' | 'default' | 'loose';
  layoutWidth:        'narrow' | 'standard' | 'full';
  // 5 hero variants
  heroLayout:         'centered' | 'split' | 'split-offset' | 'poster' | 'text-only';
  // 5 services variants
  servicesLayout:     'card-grid' | 'alternating-rows' | 'accordion' | 'two-col-feature' | 'numbered-list';
  // 5 doctor-intro variants
  aboutLayout:        'split-photo' | 'full-width-card' | 'editorial-full' | 'minimal-text' | 'two-col-brief';
  // 5 reviews variants
  testimonialsLayout: 'card-row' | 'pull-quotes' | 'single-featured' | 'list-testimonials' | 'grid-mosaic';
  // 5 CTA variants
  ctaLayout:          'centered-banner' | 'split-image' | 'inline-minimal' | 'floating-card' | 'two-button';
  // 5 FAQ variants
  faqLayout:          'accordion-expandable' | 'two-column' | 'simple-stack' | 'cards-grid' | 'split-by-category';
  // 5 nav variants — deterministic per archetype
  navVariant:         'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  // 5 footer variants
  footerVariant:      'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  // 5 gallery variants
  galleryVariant:     'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  // Visual personality signals
  typePersonality:    'grotesque' | 'display-serif' | 'humanist-serif' | 'geometric-sans';
  colorFamily:        'warm' | 'cool' | 'neutral';
}

export interface DesignDNA {
  archetype: string;
  heroVariant: 'centered' | 'asymmetric-left' | 'asymmetric-right' | 'split-image' | 'full-bleed' | 'poster';
  servicesVariant: 'cards-3up' | 'editorial-list' | 'accordion';
  navVariant: 'centered-logo' | 'left-logo' | 'split-logo' | 'transparent-overlay' | 'top-bar';
  footerVariant: 'minimal-dark' | 'editorial-split' | 'classic-4col' | 'compact-centered' | 'bold-cta-footer';
  galleryVariant: 'masonry-3col' | 'editorial-2col' | 'filmstrip' | 'featured-grid' | 'full-bleed-row';
  sectionOrder: string[];
  cardTreatment: 'bordered-flat' | 'soft-shadow' | 'elevated' | 'ghost';
  density: 'airy' | 'balanced' | 'dense';
  motion: 'none' | 'subtle' | 'expressive';
  radius: 'sharp' | 'sm' | 'md' | 'lg' | 'pill';
  borrowedFrom?: string | null;
  borrowedTrait?: string | null;
  divergenceRationale?: string;
  creativeDirection?: string;
  // typeui-style design system fields — populated by Creative Director
  typographyScale?: string;
  colorPalette?: string;
  spacingScale?: string;
  writingTone?: string;
  brandSummary?: string;
  doRules?: string[];
  dontRules?: string[];
  designTokens?: DesignTokens;
}

export const designDNA: DesignDNA = {
  "archetype": "magazine-split",
  "heroVariant": "full-bleed",
  "servicesVariant": "editorial-list",
  "navVariant": "split-logo",
  "footerVariant": "editorial-split",
  "ctaVariant": "full-width-dark",
  "doctorVariant": "portrait-left",
  "galleryVariant": "editorial-2col",
  "sectionOrder": [
    "hero",
    "stat-bar",
    "gallery",
    "doctor-intro",
    "services",
    "reviews",
    "cta",
    "faq"
  ],
  "cardTreatment": "bordered-flat",
  "density": "balanced",
  "motion": "subtle",
  "radius": "lg",
  "borrowedFrom": null,
  "borrowedTrait": "thin-rule section dividers separating each content band horizontally",
  "headingScale": "dramatic",
  "sectionDivider": "line",
  "heroTextPosition": "bottom-left",
  "divergenceRationale": "The previous build for this exact practice used editorial-asymmetric with an asymmetric-right hero — that combination is explicitly excluded. All four recent builds cluster around split-image or asymmetric-right heroes with warm-editorial or editorial-asymmetric archetypes; magazine-split with a full-bleed hero moves into a distinct layout register — wide typographic bands, bottom-left anchored credential copy, and a structured editorial grid — that none of the recent builds occupy. Warm-editorial and centered-classic were ruled out entirely as mismatched to a clinical specialist brand with FACD fellowship status.",
  "creativeDirection": "A deep-navy editorial broadsheet — credential-forward, unhurried, and architecturally precise — where Space Grotesk headlines carry institutional weight and the gold accent functions as a selective highlight on fellowship callouts and section rules, positioning Dr. Chang as a specialist referral destination rather than a neighborhood provider.",
  "coverage": {
    "filteredSections": []
  },
  "typographyScale": "serif (heading) / sans-serif (body) — scale 14/16/20/28/40/56px",
  "colorPalette": {
    "primary": "#896634",
    "secondary": "#c49451",
    "accent": "#c49451",
    "light": null,
    "raw": [
      "#c49451",
      "#896634"
    ]
  },
  "spacingScale": "4/8/16/24/48/80px",
  "writingTone": "Warm, clear, specific to Los Alamitos.",
  "brandSummary": "Russell EK Chang, DDS, MS, FACD, Inc., led by Dr. Russell Chang, serving Los Alamitos, — A deep-navy editorial broadsheet — credential-forward, unhurried, and architecturally precise — where Space Grotesk headlines carry institutional weight and the gold accent functions as a selective highlight on fellowship callouts and section rules, positioning Dr. Chang as a specialist referral destination rather than a neighborhood provider.",
  "doRules": [
    "Use the archetype's established magazine-split layout — don't mix incompatible grid styles mid-page.",
    "Hero variant must be full-bleed — lock this choice.",
    "Card treatment is bordered-flat — apply consistently across all card instances.",
    "Phone number must be a tel: link in the mobile header, minimum 44px touch target.",
    "Doctor name and credentials must appear without scrolling on the homepage.",
    "Primary CTA copy must reference a specific action and ideally the doctor or city.",
    "Body text ≥ 16px, line-height ≥ 1.5, measure 45–75 characters."
  ],
  "dontRules": [
    "No gradient text (background-clip: text) — AI-slop tell #1.",
    "No faux-glass / backdrop-filter cards unless archetype explicitly calls for it.",
    "No centered-headline + two-CTA + microlinks hero — the most overused AI pattern.",
    "No stat-bar section if yearsExperience/happyPatients data is missing — render empty = fail.",
    "No stock photography of smiling model families.",
    "No generic, boilerplate, or template-sounding copy. Every headline, tagline, and CTA must reference this specific practice, doctor, or city — never industry-generic phrasing that could appear on any competitor site.",
    "No archetype+hero combo already used in recent own-builds.",
    "No section that renders with dashes, nulls, or placeholder text visible to users."
  ],
  "designTokens": {
    "cornerRadius": "rounded",
    "buttonTreatment": "filled",
    "labelStyle": "badge",
    "sectionSpacing": "default",
    "contentDensity": "default",
    "layoutWidth": "standard",
    "heroLayout": "split-offset",
    "servicesLayout": "two-col-feature",
    "aboutLayout": "editorial-full",
    "testimonialsLayout": "single-featured",
    "ctaLayout": "floating-card",
    "faqLayout": "two-column",
    "navVariant": "split-logo",
    "footerVariant": "editorial-split",
    "galleryVariant": "editorial-2col",
    "typePersonality": "grotesque",
    "colorFamily": "cool"
  },
  "evalRationale": "Candidate 1's bordered-flat card treatment is the single most differentiating detail across all three otherwise near-identical proposals — it reinforces the broadsheet/academic-journal editorial register more precisely than soft-shadow, which reads warmer and more consumer-friendly, making it the most internally consistent with the deep-navy clinical-authority brief. The section order (gallery before doctor-intro) also better serves the conversion logic for a specialist practice where before/after evidence outweighs biography."
};

export interface ImageRoles {
  hero: string | null;
  doctorPortrait: string | null;
  team: string[];
  interior: string[];
  gallery: string[];
  beforeAfter: string[];
}

export function imagePath(role: string | null | undefined): string | null {
  if (!role) return null;
  return `/images/${role.replace(/^\/+/, '')}`;
}
