// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Russell EK Chang, DDS, MS, FACD, Inc.',
  url: 'https://changorthodontics.com',
  phone: '(562) 430-0541',
  phoneDigits: '5624300541',
  email: 'smiles@changorthodontics.com',
  googleReviewLink: '',
  googleProfileLink: '',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: 'Dr. Russell Chang',
  firstName: 'Russell',
  lastName: 'Chang',
  nameNoTitle: 'Russell Chang',
  credentials: 'DDS, MS, FACD',
  bio: "Dr. Russell Chang is well known in the Los Alamitos community and beyond as a warm and caring professional who delivers outstanding orthodontic results. He works closely with both general dentists and specialists to provide the Chang Signature Smile for each patient. Dr. Chang follows in both his father's and grandfather's footsteps. His grandfather, Dr. Sau Yee Chang, was the first dentist on the island of Kauai and first Chinese American to be Vice President of the American Dental Association. Dr. Chang graduated from his grandfather's alma mater, Northwestern University completing his residency in Orthodontics and Masters of Science degree in Cranial Facial Biology. Dr. Chang graduated high school from the Punahou School in Oahu, Hawaii. He completed his undergraduate studies and earned his dental degree from the University of Southern California. He has three wonderful children with his wife Dr. Stephanie Dodson Chang, a periodontist. In addition to being a long term member of the Cleft Lip and Palate Team at Miller Children's Hospital in Long Beach, Dr. Chang has served as a lecturer and assistant professor in the Orthodontic Departments of the University of Southern California and the University of California, Los Angeles Schools of Dentistry. Dr. Chang also works with the Stramsky Center for Craniofacial Development at Miller Children's Hospital. Technology, the most advanced clinical techniques, and instrumentation are critical to the outstanding results delivered by Dr. Chang and his Team. Attending many meetings both locally and internationally is a part of his routine on a frequent basis to keep ChangOrthodontics at the cutting edge of the art and science of orthodontic treatment.",
};

export const additionalDoctors = [
  {
    "name": "Dr. Christine Chung",
    "firstName": "Christine",
    "lastName": "Chung",
    "nameNoTitle": "Christine Chung",
    "credentials": "DMD, MS",
    "bio": "Dr. Christine Chung came to California in 1991 after being raised in São Paulo, Brazil. She graduated Magna Cum Laude from the University of California, Los Angeles in 1995 and completed her dental education at Harvard School of Dental Medicine, with honors. Dr. Chung completed her orthodontic specialty residency at the University of California School of Dentistry, where she concurrently earned a Master of Science degree in Craniofacial Biology. She enjoys working with patients of all ages and takes great pride in treating each patient like her own family. Dr. Chung feels tremendously privileged to have the opportunity to create beautiful smiles.",
    "education": "USC Adjunct Assistant Professor of Postdoctoral Orthodontics and Pediatric Dentistry",
    "specialties": [
      "Orthodontics",
      "Pediatric Dentistry",
      "Craniofacial Biology",
      "Orthodontic Training",
      "Surgical Orthodontics",
      "Dentofacial Orthopedics"
    ],
    "photoPath": "/assets/uploads/images/meet-dr-christine-chung.jpg"
  }
];

export const doctors = [doctor, ...additionalDoctors];



export const address = {
  street: '4608 Katella Ave STE 201',
  city: 'Los Alamitos',
  state: 'CA',
  zip: '90720',
  country: 'US',
  full: '4608 Katella Ave STE 201, Los Alamitos, CA 90720',
};

export const hours = {
  display: [

  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'sameAs': [
    site.googleProfileLink,
    'https://www.facebook.com/changortho/',
    'https://www.instagram.com/changorthodontics/',
    'https://twitter.com/DrChangOrtho',
    'http://search.google.com/local/writereview?placeid=ChIJLU275-0u3YARKvs_iQAweo8',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DDS, MS, FACD Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  'description': doctor.bio,
  'alumniOf': 'USC Adjunct Assistant Professor of Postdoctoral Orthodontics',
  'knowsAbout': ["Orthodontics","Craniofacial Orthodontics","Cleft Lip and Palate","Dentofacial Orthopedics"],
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));

