/**
 * Clone the starter template and inject all config files from merged PracticeData.
 *
 * This module generates complete TypeScript/JS config files (not string-replace)
 * and sweeps .astro/.md files for placeholder tokens.
 */

import { cp, readFile, writeFile, mkdir, readdir, stat } from 'node:fs/promises';
import { resolve, dirname, join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { glob } from 'glob';
import { DEFAULT_HOURS, DEFAULT_COLORS } from './schema.js';
import { esc } from './utils.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Template root is 3 levels up from this file (scripts/pipeline/lib -> project root) */
const TEMPLATE_ROOT = resolve(__dirname, '../../..');

/** Directories / files to skip when cloning the template */
const CLONE_EXCLUDE = new Set([
  'node_modules',
  'dist',
  '.git',
  'scripts/pipeline',
]);

// ---------------------------------------------------------------------------
// Main orchestrator
// ---------------------------------------------------------------------------

/**
 * Clone the template into outputDir and inject all configuration.
 *
 * @param {object} data      - Complete PracticeData from merger.
 * @param {string} outputDir - Absolute path to the target directory.
 * @param {object} [preset]  - Loaded vertical preset (from preset-loader).
 */
export async function injectTemplate(data, outputDir, preset = null) {
  console.log(`[injector] Cloning template into ${outputDir}`);
  await cloneTemplate(TEMPLATE_ROOT, outputDir);

  console.log('[injector] Injecting site config');
  await injectSiteConfig(data, outputDir, preset);

  console.log('[injector] Injecting navigation');
  await injectNavigation(data, outputDir);

  console.log('[injector] Injecting Tailwind config');
  await injectTailwindConfig(data, outputDir);

  console.log('[injector] Injecting Astro config');
  await injectAstroConfig(data, outputDir);

  console.log('[injector] Injecting deploy config');
  await injectDeployConfig(data, outputDir);

  console.log('[injector] Injecting content config');
  await injectContentConfig(data, outputDir);

  console.log('[injector] Replacing page placeholders');
  await injectPagePlaceholders(data, outputDir);

  console.log('[injector] Done.');
}

// ---------------------------------------------------------------------------
// Clone helper
// ---------------------------------------------------------------------------

async function cloneTemplate(srcRoot, destRoot) {
  await mkdir(destRoot, { recursive: true });

  const entries = await readdir(srcRoot, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = join(srcRoot, entry.name);
    const destPath = join(destRoot, entry.name);

    // Compute the relative path from the template root for exclusion checks
    const relFromRoot = relative(TEMPLATE_ROOT, srcPath);

    // Check if this entry (or a parent path) is in the exclusion set
    const shouldExclude = [...CLONE_EXCLUDE].some(
      ex => relFromRoot === ex || relFromRoot.startsWith(ex + '/')
    );
    if (shouldExclude) continue;

    if (entry.isDirectory()) {
      await cloneTemplate(srcPath, destPath);
    } else {
      await mkdir(dirname(destPath), { recursive: true });
      await cp(srcPath, destPath);
    }
  }
}

// ---------------------------------------------------------------------------
// site.ts
// ---------------------------------------------------------------------------

export async function injectSiteConfig(data, outputDir, preset = null) {
  const p = data.practice;
  const d = data.doctor;
  const a = data.address;
  const h = data.hours || DEFAULT_HOURS;

  const hoursDisplay = (h.display || DEFAULT_HOURS.display)
    .map(e => `    { day: '${esc(e.day)}', time: '${esc(e.time)}' },`)
    .join('\n');

  const hoursSchema = (h.schema || DEFAULT_HOURS.schema)
    .map(s => `'${esc(s)}'`)
    .join(', ');

  const sameAs = (p.sameAs || [])
    .filter(Boolean)
    .map(url => `    '${esc(url)}',`)
    .join('\n');

  const sameAsBlock = sameAs
    ? `[\n    site.googleProfileLink,\n${sameAs}\n  ]`
    : `[\n    site.googleProfileLink,\n  ]`;

  const businessType = preset?.schema?.businessType || 'Dentist';
  const defaultCredentials = preset?.schema?.defaultCredentials || 'DDS';

  const content = `// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: '${esc(p.name || '')}',
  url: 'https://${esc(p.domain || 'example.com')}',
  phone: '${esc(p.phone || '')}',
  phoneDigits: '${esc(p.phoneDigits || '')}',
  email: '${esc(p.email || '')}',
  googleReviewLink: '${esc(p.googleReviewLink || '')}',
  googleProfileLink: '${esc(p.googleProfileLink || '')}',
};

export const doctor = {
  name: '${esc(d.name || '')}',
  firstName: '${esc(d.firstName || '')}',
  lastName: '${esc(d.lastName || '')}',
  credentials: '${esc(d.credentials || defaultCredentials)}',
};

export const address = {
  street: '${esc(a.street || '')}',
  city: '${esc(a.city || '')}',
  state: '${esc(a.state || '')}',
  zip: '${esc(a.zip || '')}',
  country: '${esc(a.country || 'US')}',
  full: '${esc(a.full || '')}',
};

export const hours = {
  display: [
${hoursDisplay}
  ],
  schema: [${hoursSchema}],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': '${esc(businessType)}',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '${esc(p.priceRange || '$$')}',${
    p.medicalSpecialty
      ? `\n  'medicalSpecialty': '${esc(p.medicalSpecialty)}',`
      : ''
  }
  'sameAs': ${sameAsBlock},
};
`;

  const filePath = resolve(outputDir, 'src/config/site.ts');
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// navigation.ts
// ---------------------------------------------------------------------------

export async function injectNavigation(data, outputDir) {
  const hubs = data.services?.hubs || [
    { slug: 'general-dentistry', label: 'General Dentistry', desc: 'Cleanings, exams & preventive care' },
  ];

  const serviceDropdown = hubs
    .map(
      h =>
        `      { label: '${esc(h.label)}', href: '/services/${esc(h.slug)}', desc: '${esc(h.desc)}' },`
    )
    .join('\n');

  const content = `// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  avatar?: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About Us', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    dropdown: [
${serviceDropdown}
    ],
  },
  {
    label: 'Resources',
    href: '/blog',
    dropdown: [
      { label: 'Patient Blog', href: '/blog', desc: 'Education & treatment guides' },
      { label: 'Before & After', href: '/gallery', desc: 'Real patient results' },
      { label: 'FAQ', href: '/faq', desc: 'Common questions answered' },
      { label: 'Financing', href: '/financing', desc: 'Insurance & payment options' },
    ],
  },
];
`;

  const filePath = resolve(outputDir, 'src/config/navigation.ts');
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// tailwind.config.mjs
// ---------------------------------------------------------------------------

export async function injectTailwindConfig(data, outputDir) {
  const colors = data.brand?.colors || DEFAULT_COLORS;
  const fonts = data.brand?.fonts || { heading: 'Playfair Display', body: 'DM Sans' };

  const content = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '${esc(colors.primary || DEFAULT_COLORS.primary)}',
          secondary: '${esc(colors.secondary || DEFAULT_COLORS.secondary)}',
          light: '${esc(colors.light || DEFAULT_COLORS.light)}',
          accent: '${esc(colors.accent || DEFAULT_COLORS.accent)}',
          highlight: '${esc(colors.highlight || DEFAULT_COLORS.highlight)}',
        },
        neutral: {
          dark: '#1A1A1A',
          mid: '#4A4A4A',
          light: '#F8F9FA',
          border: '#E0E0E0',
        },
        surface: {
          1: '#FFFFFF',
          2: '#F7F6F3',
        },
        charcoal: '#111111',
        'mid-gray': '#666666',
        'border-light': '#E5E4E0',
      },
      fontFamily: {
        serif: ['${esc(fonts.heading || 'Playfair Display')}', 'Georgia', 'serif'],
        sans: ['${esc(fonts.body || 'DM Sans')}', 'system-ui', 'sans-serif'],
      },
    },
  },
};
`;

  const filePath = resolve(outputDir, 'tailwind.config.mjs');
  await writeFile(filePath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// astro.config.mjs
// ---------------------------------------------------------------------------

export async function injectAstroConfig(data, outputDir) {
  const domain = data.practice?.domain || 'example.com';
  const siteUrl = `https://${domain}`;

  const hubPaths = (data.services?.hubs || [])
    .map(h => `'/${h.slug}/'`)
    .join(', ');

  const content = `import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: '${esc(siteUrl)}',
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/thank-you'),
      serialize(item) {
        const siteUrl = '${esc(siteUrl)}';
        if (item.url === siteUrl + '/') {
          return { ...item, priority: 1.0, changefreq: 'weekly' };
        }
        const highPriority = [${hubPaths ? hubPaths + ', ' : ''}'/about'];
        if (highPriority.some(p => item.url.endsWith(p) || item.url.endsWith(p + '/'))) {
          return { ...item, priority: 0.9, changefreq: 'weekly' };
        }
        if (item.url.includes('/blog/') && !item.url.replace(siteUrl + '/blog/', '').includes('/')) {
          return { ...item, priority: 0.7, changefreq: 'weekly' };
        }
        if (item.url.includes('/blog/')) {
          return { ...item, priority: 0.6, changefreq: 'monthly' };
        }
        return { ...item, priority: 0.8, changefreq: 'monthly' };
      },
    }),
    tailwind(),
  ],
});
`;

  const filePath = resolve(outputDir, 'astro.config.mjs');
  await writeFile(filePath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// .github/workflows/deploy.yml
// ---------------------------------------------------------------------------

export async function injectDeployConfig(data, outputDir) {
  const deployPath = resolve(outputDir, '.github/workflows/deploy.yml');

  let content;
  try {
    content = await readFile(deployPath, 'utf-8');
  } catch {
    // No deploy file in the cloned output — nothing to patch
    return;
  }

  const domain = data.practice?.domain || 'example.com';
  const projectName = domain.replace(/\./g, '-');

  content = content.replace(/https:\/\/\[DOMAIN\]/g, `https://${domain}`);
  content = content.replace(/\[DOMAIN\]/g, domain);
  content = content.replace(/\[PROJECT_NAME\]/g, projectName);

  await writeFile(deployPath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// content/config.ts  (update default author)
// ---------------------------------------------------------------------------

export async function injectContentConfig(data, outputDir) {
  const configPath = resolve(outputDir, 'src/content/config.ts');

  let content;
  try {
    content = await readFile(configPath, 'utf-8');
  } catch {
    return;
  }

  const practiceName = data.practice?.name || '';
  if (practiceName) {
    content = content.replace(
      /\.default\(['"].*?['"]\)/g,
      `.default('${esc(practiceName)}')`
    );
  }

  await writeFile(configPath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// Placeholder sweep across .astro and .md files
// ---------------------------------------------------------------------------

export async function injectPagePlaceholders(data, outputDir) {
  const patterns = [
    resolve(outputDir, 'src/**/*.astro'),
    resolve(outputDir, 'src/**/*.md'),
  ];

  let files = [];
  for (const pattern of patterns) {
    const matches = await glob(pattern, { nodir: true });
    files = files.concat(matches);
  }

  // Build replacement map from data
  const city = data.address?.city || '';
  const state = data.address?.state || '';
  const practiceName = data.practice?.name || '';
  const doctorFirst = data.doctor?.firstName || '';
  const doctorLast = data.doctor?.lastName || '';
  const credentials = data.doctor?.credentials || 'DDS';
  const domain = data.practice?.domain || 'example.com';
  const street = data.address?.street || '';
  const zip = data.address?.zip || '';

  // Stats replacements — replace [X]+ patterns near known stat labels
  const stats = data.content?.stats || {};

  const replacements = [
    // Exact bracket placeholders
    [/\[CITY\]/g, city],
    [/\[STATE\]/g, state],
    [/\[PRACTICE_NAME\]/g, practiceName],
    [/\[FIRST_NAME\]/g, doctorFirst],
    [/\[LAST_NAME\]/g, doctorLast],
    [/\[CREDENTIALS\]/g, credentials],
    [/\[DOMAIN\]/g, domain],
    [/\[STREET_ADDRESS\]/g, street],
    [/\[ZIP\]/g, zip],
    [/\[YOUR_GOOGLE_REVIEW_ID\]/g, extractGoogleId(data.practice?.googleReviewLink) || 'YOUR_GOOGLE_REVIEW_ID'],
    [/\[YOUR_GOOGLE_PROFILE_ID\]/g, extractGoogleId(data.practice?.googleProfileLink) || 'YOUR_GOOGLE_PROFILE_ID'],
  ];

  for (const filePath of files) {
    let content = await readFile(filePath, 'utf-8');
    let changed = false;

    for (const [pattern, replacement] of replacements) {
      const before = content;
      content = content.replace(pattern, replacement);
      if (content !== before) changed = true;
    }

    // Replace stat [X]+ placeholders with actual values when available
    if (stats.yearsExperience) {
      const before = content;
      content = content.replace(
        /(\[X\]\+)([\s\S]{0,40}Years?\s*Experience)/gi,
        `${stats.yearsExperience}+$2`
      );
      if (content !== before) changed = true;
    }
    if (stats.happyPatients) {
      const before = content;
      content = content.replace(
        /(\[X\]\+)([\s\S]{0,40}Happy\s*Patients?)/gi,
        `${stats.happyPatients}+$2`
      );
      if (content !== before) changed = true;
    }
    if (stats.fiveStarReviews) {
      const before = content;
      content = content.replace(
        /(\[X\]\+)([\s\S]{0,40}5[- ]?Star\s*Reviews?)/gi,
        `${stats.fiveStarReviews}+$2`
      );
      if (content !== before) changed = true;
    }

    // Replace any remaining [X]+ with a safe placeholder
    {
      const before = content;
      content = content.replace(/\[X\]\+/g, '—');
      if (content !== before) changed = true;
    }

    if (changed) {
      await writeFile(filePath, content, 'utf-8');
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Extract the Google Place ID from a g.page URL.
 * e.g. 'https://g.page/r/CU4itT3RNhmQEBM/review' -> 'CU4itT3RNhmQEBM'
 */
function extractGoogleId(url) {
  if (!url) return null;
  const match = url.match(/\/r\/([^/]+)/);
  return match ? match[1] : null;
}
