// Navigation link structure for Header.astro
// Auto-generated by the build pipeline — do not edit manually.
// NOTE: The AI-generated Header.astro may build its own nav from site config + DNA.
// This file serves as a structured reference and fallback.

export interface NavDropdownItem {
  label: string;
  href: string;
  desc?: string;
}

export interface NavLink {
  label: string;
  href: string;
  dropdown?: NavDropdownItem[];
}

export const navLinks: NavLink[] = [
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services', dropdown: [{ label: '3shape Digital Scanner', href: '/services/3shape-digital-scanner', desc: '3shape digital intraoral scanner for precise digital impressions.' }, { label: 'All-on-4', href: '/services/all-on-4', desc: 'A revolutionary implant procedure that completely replaces an entire arch of teeth using only four implants.' }, { label: 'Bone Grafts', href: '/services/bone-grafts', desc: 'Bone grafting procedures, typically performed to prepare the jaw for dental implants.' }, { label: 'Bridges', href: '/services/bridges', desc: 'Dental bridges to replace one or more missing teeth by anchoring to adjacent natural teeth.' }, { label: 'Brushing & Flossing Instruction', href: '/services/brushing-flossing-instruction', desc: 'Oral hygiene instruction for pediatric patients and their parents on proper brushing and flossing techniques.' }, { label: 'CandidPro', href: '/services/candidpro', desc: 'CandidPro clear aligner treatment option available at Arizona Biltmore Dentistry.' }, { label: 'Children\'s Exams & Cleanings', href: '/services/children-s-exams-cleanings', desc: 'Comprehensive oral exams and cleanings for pediatric patients, including a risk assessment for cavities.' }, { label: 'Clear Aligners', href: '/services/clear-aligners', desc: 'An \'invisible\' type of braces that uses a series of clear, removable aligners to move teeth into alignment, available for adults and teens.' }, { label: 'All Services', href: '/services' }] },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQ', href: '/faq' },
];
