// Central source of truth for practice information.
// Auto-generated by the build pipeline — do not edit manually.

export const site = {
  name: 'Arizona Biltmore Dentistry',
  url: 'https://www.arizonabiltmoredentistry.com',
  phone: '(602) 957-8200',
  phoneDigits: '6029578200',
  email: 'info@arizonabiltmoredentistry.com',
  googleReviewLink: 'https://maps.google.com/?cid=10483446600579265121',
  googleProfileLink: 'https://maps.google.com/?cid=10483446600579265121',
};

export const doctor = {
  // `name` includes the title prefix (e.g. "Dr. Anthony Hoang"). Use it as-is.
  // For copy that already provides a title, use `nameNoTitle` instead.
  name: 'Dr. Aaron Jeziorski',
  firstName: 'Aaron',
  lastName: 'Jeziorski',
  nameNoTitle: 'Aaron Jeziorski',
  credentials: 'DMD',
  // Bio MUST come from the doctor's own about/bio page. We never fall back to
  // practice.aboutText / mission copy — that produces the "bio bleed" bug
  // where the practice's philosophy ends up posing as a doctor's biography.
  bio: "Dr. Jeziorski is an Arizona native who thrives on brightening the smiles of all his patients. He has a Bachelor of Science in Kinesiology. After his undergraduate studies, he attended the Arizona School of Dentistry and Oral Health through A.T. Still University where he earned his Doctor of Dental Medicine degree. Dr. Jeziorski is passionate about dental education, he regularly attends seminars and conferences to continue his own dental education and expertise. He also provides guidance to dental students at the Central Arizona Shelter Services Dental Clinic for the Homeless.\n\nA family man, Dr. Jeziorski married his soulmate, Chrissy, in 2007, and together they have four children. When he's not in the office, he enjoys spending time with his family. Dr. Jeziorski provides his personal cell phone number to his patients to ensure they always have access to the care they need. Now that's dedication!",
};

// Additional doctors — secondary clinicians at the practice. Templates that
// support multi-doctor display (about.astro, team page) iterate this array.
// Empty for single-doctor practices.
// (Back-compat mirror of doctors[1..] — new templates should use `doctors` directly.)
export const additionalDoctors = [
  {
    "name": "Dr. Michael Hood",
    "firstName": "Michael",
    "lastName": "Hood",
    "nameNoTitle": "Michael Hood",
    "credentials": "",
    "bio": "A fourth-generation Arizonan, Dr. Hood attended Arizona State University, followed by the esteemed Baylor College of Dentistry in Dallas, Texas. He has performed countless cosmetic dental procedures and is certified and licensed to use the FDA-approved LANAP® and Periolase® procedures to treat gum disease. He is also Invisalign® certified and trained in dental sleep medicine to aid his patients suffering from sleep apnea and snoring.\n\nDr. Hood is married with four children. He enjoys spending time with his wife and children when he's not in the office.",
    "education": "Arizona State University; Baylor College of Dentistry — Dallas, Texas",
    "specialties": [
      "Cosmetic Dentistry",
      "Periodontal Disease Treatment",
      "Dental Sleep Medicine"
    ],
    "photoPath": null
  },
  {
    "name": "Dr. Nguyen",
    "firstName": "Nguyen",
    "lastName": "Nguyen",
    "nameNoTitle": "Nguyen",
    "credentials": "DMD",
    "bio": "Dr. Nguyen is originally from Ventura, California. After studying Physiology at UCLA, she obtained a Masters degree and Doctor of Dental Medicine degree from Midwestern University, Arizona. She now resides in Phoenix with her husband. Dr. N is passionate about dentistry and strives to provide each patient with a positive and comfortable dental experience. Outside of the office, she enjoys reading, Pilates, and scouring the Valley for the best foods and drinks.",
    "education": "Physiology — UCLA; Masters degree — Midwestern University, Arizona; Doctor of Dental Medicine — Midwestern University, Arizona",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Gregory Fuller",
    "firstName": "Gregory",
    "lastName": "Fuller",
    "nameNoTitle": "Gregory Fuller",
    "credentials": "",
    "bio": "I am a native Arizonan and I have lived all over the State of Arizona. I call the Phoenix area my home town. I am the oldest of five children. My wife of thirty years and I survived a blended family of five children which was very challenging yet satisfying. We persevered with a sense of humor! Some of you know \"la chancla\". My children learned very quickly about a Latin mother!\n\nI graduated with distinction from Arizona State University with a Bachelor of Science in Business Management and Marketing. I spent another three years obtaining my pre-dental requirements before I applied to dental school. I was fortunate to be accepted to the number one clinical school in the country, the University of the Pacific Arthur A Dugoni School of Dentistry. Later in my career I mentored several new dental school graduates and found teaching to be very fulfilling. I practiced many years in Tucson, Arizona, and owned a very successful private practice which I sold in 2019 and then mo\n\nTen months later, I realized I missed dentistry and felt the need to practice my chosen profession. I have been working part time ever since and I am very excited to call Arizona Biltmore Dentistry to be home. The first day at Biltmore, I knew I found a practice that matched my dental expectations. Very impressed with the staff and the depth of their knowledge and wanting to do their very best for the patients' needs. I find cosmetics and full mouth rehabs to be life changing for the patient, which is very gratifying. Implants and jaw bone preservation is another area I find to be a great serv\n\nMy hobbies are rebuilding old muscle cars, hiking and bicycling. Also, I have been hands on in remodeling several homes. I love the creativity! My wife and I enjoy traveling and hanging with our two grandsons and two granddaughters. Life is good!",
    "education": "Bachelor of Science in Business Management and Marketing — Arizona State University (graduated with distinction); Doctor of Dentistry — University of the Pacific Arthur A Dugoni School of Dentistry",
    "specialties": [
      "Cosmetics",
      "Full Mouth Rehabilitation",
      "Implants",
      "Jaw Bone Preservation"
    ],
    "photoPath": null
  },
  {
    "name": "Dr. Ekaterina Pollard",
    "firstName": "Ekaterina",
    "lastName": "Pollard",
    "nameNoTitle": "Ekaterina Pollard",
    "credentials": "",
    "bio": "I am a graduate of the Herman Ostrow School of Dentistry of the University of Southern California in Los Angeles. I received the \"Head of Class\" Top Student Award when I graduated in 2001. Due to this distinguishing honor, immediately after graduation I was invited to work at a prestigious dental office in Beverly Hills, where I gained valuable experience in meeting the needs of patients. I found it very rewarding to see some of my patients on \"The Big Screen\" and to know that \"Hollywood Smile\" was thanks to my efforts in giving them the best dental care possible!\n\nIn 2003, I relocated to Arizona in order to escape the infamous traffic and hustle and bustle of Southern California. I owned a private dental practice for five years and have over 20 years of dental experience. In my free time, I enjoy hiking and time with my son.\n\nI look forward to joining the Arizona Biltmore team in providing the quality of care that you expect from this office, as well as the care you deserve.",
    "education": "Doctor of Dentistry — Herman Ostrow School of Dentistry, University of Southern California, Los Angeles (2001)",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Rozita Esbah, DMD",
    "firstName": "Rozita",
    "lastName": "Esbah",
    "nameNoTitle": "Rozita Esbah, DMD",
    "credentials": "DMD",
    "bio": "Dr. Rozita Esbah graduated from Prestigious Tufts University School of Dental Medicine in 2001 and has practiced in private dental offices ever since. She moved to Phoenix in 2007, where she continues to provide compassionate, patient-focused care. Dr. Esbah is passionate about helping patients feel comfortable, especially those who experience dental anxiety. Her gentle approach and reassuring manner help patients build trust and feel at ease during their visits. Outside the office, she enjoys life in Arizona with her husband and their two daughters. Dr. Esbah looks forward to welcoming you and helping you achieve a healthy, confident smile.",
    "education": "Doctor of Dental Medicine — Tufts University School of Dental Medicine (2001)",
    "specialties": [
      "Dental Anxiety Management"
    ],
    "photoPath": null
  },
  {
    "name": "Dr. Matthew Rucker",
    "firstName": "Matthew",
    "lastName": "Rucker",
    "nameNoTitle": "Matthew Rucker",
    "credentials": "DMD",
    "bio": "Dr. Matthew Rucker was born in Phoenix, Arizona and was raised in Las Vegas. Upon graduating high school, he went off to the United States Marines where he served a total of eight years on active duty and served two combat tours to Iraq. Leaving the Marines in 2011, he pursued a professional degree in dentistry. Dr. Matt received his Bachelor of Science in Biology at UNLV and continued to his Doctor of Dental Medicine degree at UNLV. During his journey to higher learning, Dr. Rucker met his beautiful wife, Dr. Taylor Rucker. They share four wonderful children together.\n\nDr. Matthew Rucker's mission in clinical dentistry is to achieve the utmost excellence in patient care. Listening to your dental needs and providing the service that addresses those needs is important to him.",
    "education": "Bachelor of Science in Biology — UNLV; Doctor of Dental Medicine — UNLV",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Rodriguez",
    "firstName": "Rodriguez",
    "lastName": "Rodriguez",
    "nameNoTitle": "Rodriguez",
    "credentials": "",
    "bio": "",
    "education": "",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Leonard",
    "firstName": "Leonard",
    "lastName": "Leonard",
    "nameNoTitle": "Leonard",
    "credentials": "",
    "bio": "",
    "education": "",
    "specialties": [],
    "photoPath": null
  },
  {
    "name": "Dr. Dang",
    "firstName": "Dang",
    "lastName": "Dang",
    "nameNoTitle": "Dang",
    "credentials": "",
    "bio": "",
    "education": "",
    "specialties": [],
    "photoPath": null
  }
];

// Unified doctors[] — primary first, then additionalDoctors. Use this when
// you want to render ALL doctors uniformly (e.g. team page, multi-doctor
// "Meet Our Doctors" section).
export const doctors = [doctor, ...additionalDoctors];

// Non-doctor staff (hygienists, dental assistants, receptionists, office
// managers). Rendered as the supporting team on /about and /team pages.
// Empty for practices with no staff captured.
export const staff = [
  {
    "name": "Stacey",
    "role": "assistant",
    "bio": "",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Ericka",
    "role": "assistant",
    "bio": "The absolute best dental technician i have ever had is Dr Jeziorski's---Ericka---through the whole process she is reassuring --so knowledgable--and personable. She was with me through the entire process--kept me informed --. Erika supports you and cares about your comfort.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Omar",
    "role": "hygienist",
    "bio": "Omar was there for my first appointment and took his time to talk through treatment options, recommendations, and give me dental hygiene skills.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Brittnie",
    "role": "hygienist",
    "bio": "Brittnie was very kind and efficient. She took exceptionally good care of me as I had my first ever crown placed.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Annie",
    "role": "hygienist",
    "bio": "Annie was the third dental hygienist that I saw for my second crown placement. She isn't a permanent staff member (coming in as needed) but I wish she was! She took her time cleaning my teeth and prepping for the second crown and since there was some extra time before we got started with the procedure, she took advantage of it to help clean a strain in the front of my teeth that formed after a chip. This was above and beyond anything I could have asked for!",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Jason",
    "role": "assistant",
    "bio": "Jason care for me for my first evaluation and and first cleaning/temp crown placement, but even when I was with Zenovia he went out of his way to check on me and chat. He is extremely personable, talented, and enthusiastic.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Zenovia",
    "role": "assistant",
    "bio": "Zenovia completed my second cleaning/temp crown and the permanent crown placements. She, like Jason, was so kind and empathetic. I was confident in her abilities and she offered some of the kindest compliments I have received.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Nick",
    "role": "assistant",
    "bio": "I was also so fortunate to be care for by Nick for a quick drop in. I was having some tooth aches after my second temp crown and Nick quickly identified and corrected the issue to allow me to sleep pain free!",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "LC",
    "role": "receptionist",
    "bio": "LC was not only approachable (as someone at the front desk should be) but was enjoyable. For one appointment, I came in an hour early on accident, and LC was more than happy to help me understand my charges and the dental benefits coverage. Her service was beyond exceptional.",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Karla",
    "role": "receptionist",
    "bio": "Karla is the reason that all of my scheduling was well accommodated and that any administrative questions were addressed. Every time I was getting ready to leave she greeted me with a warm smile that radiated beyond her mask and scheduled me for the best follow up appointment as needed. She was absolutely wonderful!",
    "credentials": "",
    "photoPath": null
  },
  {
    "name": "Gretchen",
    "role": "other",
    "bio": "Gretchen was amazing and professional with conversation and getting the job done.",
    "credentials": "",
    "photoPath": null
  }
];

export const address = {
  street: '2777 E Camelback Road, Ste. 101',
  city: 'Phoenix',
  state: 'AZ',
  zip: '85016',
  country: 'US',
  full: '2777 E Camelback Road, Ste. 101, Phoenix, AZ 85016',
};

export const hours = {
  display: [
    { day: 'Mon', time: '7 AM - 5 PM' },
    { day: 'Tue', time: '7 AM - 5 PM' },
    { day: 'Wed', time: '7 AM - 5 PM' },
    { day: 'Thu', time: '7 AM - 5 PM' },
    { day: 'Fri', time: '7 AM - 4 PM' },
    { day: 'Sat', time: '7 AM - 2 PM' },
  ],
  schema: ['Mo-Fr 09:00-17:00'],
};

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dentist',
  'name': site.name,
  'url': site.url,
  'telephone': site.phone,
  'address': {
    '@type': 'PostalAddress',
    'streetAddress': address.street,
    'addressLocality': address.city,
    'addressRegion': address.state,
    'postalCode': address.zip,
    'addressCountry': address.country,
  },
  'openingHours': hours.schema,
  'priceRange': '$$',
  'aggregateRating': {
    '@type': 'AggregateRating',
    'ratingValue': 4.7,
    'reviewCount': 1342,
    'bestRating': 5,
  },
  'sameAs': [
    site.googleProfileLink,
    'https://www.linkedin.com/company/arizona-biltmore-dentistry',
    'https://www.facebook.com/arizonabiltmoredentistry?fref=ts',
    'https://plus.google.com/+Arizonabiltmoredentistry',
    'https://www.yelp.com/biz/arizona-biltmore-dentistry-phoenix',
    'https://twitter.com/AZBiltmore',
    'https://www.youtube.com/channel/UC3jj0nOhAv1mMHxlWFN49AQ',
    'https://www.yelp.com/biz/arizona-biltmore-dentistry-phoenix?sort_by=date_desc',
    'https://goo.gl/maps/gA2ArbkW6iQ2',
    'https://maps.google.com/?cid=10483446600579265121',
  ],
};

// Person schema for the practice's primary doctor — used on the about page
// and any page that profiles the doctor specifically.
// (Back-compat scalar; new code should iterate `personSchemas[]` instead.)
export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doctor.name,
  'jobTitle': 'DMD Dentist',
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  'description': doctor.bio,
  'alumniOf': 'Bachelor of Science in Kinesiology; Doctor of Dental Medicine — Arizona School of Dentistry and Oral Health, A.T. Still University',
  'knowsAbout': ["Oral Surgery","Full Mouth Restoration","Aesthetic Dentistry","Emergency Services","Anesthesia Services","Dental Implants","All-on-4"],
};

// Person schemas for ALL doctors — one entry per clinician. Use this on
// /about/ (so search engines see every doctor as a Person entity) and on
// per-doctor /team/<slug>/ pages. `personSchema` (singular, above) remains
// for back-compat = personSchemas[0].
export const personSchemas = doctors.map((doc) => ({
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': doc.name,
  'jobTitle': `${(doc.credentials || 'DDS').trim()} Dentist`,
  'worksFor': {
    '@type': 'Dentist',
    'name': site.name,
    'url': site.url,
    'address': localBusinessSchema.address,
  },
  ...(doc.bio       ? { 'description': doc.bio } : {}),
  ...(doc.education ? { 'alumniOf':   doc.education } : {}),
  ...(doc.specialties && doc.specialties.length ? { 'knowsAbout': doc.specialties } : {}),
  ...(doc.photoPath ? { 'image': doc.photoPath } : {}),
}));
